/**
 **  Macro to run the offline for all the detectors simultaneously
 **
 **  One needs to set up the Phase0 experiments, in this case s455
 **
 **  This macro takes the root files generated by the unpack_offline macro
 **  and processes the mapped data to get the next data levels (Cal and hit)
 **
 **  Author: Jose Luis <joseluis.rodriguez.sanchez@usc.es>
 **  @since May 4th, 2021
 **
 **  Modified: Gabriel Garcia <gabrielgarcia.jimenez@usc.es>
 **  @ October 7th, 2021
 **  const Int_t nev = -1; number of events to read, -1 - until CTRL+C
 **  Select experiment ID: 444, 467 or 455
 **
 **  After defining the input file (filename), execute the macro
 **  1) if all the parameters are right by default
 **     root -l cal_offline.C
 **  2) if one wants to select a RunId, for instance 'RunId = 273'
 **     root -l 'cal_offline.C(273)'
 **  3) if one wants to select a RunId and max number of events,
 **     for instance 'RunId = 273' and 'nev = 200'
 **     root -l 'cal_offline.C(273,200)'
 **  4) if one wants to select a RunId, max number of events and ExpId,
 **     for instance 'RunId = 273', 'nev = 200', and 'ExpId = 444'
 **     root -l 'cal_offline.C(273,200,444)'
 **  Points (2), (3) and (4) are used only if runid file (setup_runid.par)
 **  is not defined
 **
 **/

struct metafile_data_struct {

  Int_t fRunID;
  Int_t fExpRun;
  int64_t fTimeStamp;

  Int_t califaMapVersion;
  Int_t califaCalVersion;
  Int_t califaGeoVersion;

};

TString lookforfile();

void cal_offline()
{
  FairLogger::GetLogger()->SetLogScreenLevel("INFO");
  FairLogger::GetLogger()->SetColoredLog(true);



  // File names and paths -----------------------------------------------------
  TString filename, outputFilename;

  filename = "main0023_mapped.root";
  outputFilename = "main0023_cal.root";

  Int_t nev = -1;
  // Setup: Selection of detectors
  Bool_t fAms = false;     // AMS tracking detectors
  Bool_t fCalifa = true;   // Califa calorimeter


  // Create run  --------------------------------------------------------------
  FairRunAna *run = new FairRunAna();
  // Set up R3BHeader  --------------------------------------------------------
  R3BEventHeader *EvntHeader = new R3BEventHeader();
  run->SetEventHeader(EvntHeader);

  run->SetSink(new FairRootFileSink(outputFilename));

  // Runtime data base ------------------------------------
  FairRuntimeDb *rtdb = run->GetRuntimeDb();

  /* ------------- Set Parameter File ----------------*/

  TString calibrationFile = "../../../workshop_expParams.root";
  calibrationFile.ReplaceAll("//", "/");

  /* -------------- Set Parameter Containers ---------- */
  R3BCalifaCrystalCalPar *califaCalPar;
  R3BCalifaMappingPar *califaMapPar;
  R3BTGeoPar *califaGeoPar;

  FairParRootFileIo *parIo1 = new FairParRootFileIo(kFALSE);

  califaCalPar = (R3BCalifaCrystalCalPar *)rtdb->getContainer("califaCrystalCalPar");
  califaMapPar = (R3BCalifaMappingPar *)rtdb->getContainer("califaMappingPar");
  califaGeoPar = (R3BTGeoPar *)rtdb->getContainer("CalifaGeoPar");

  parIo1->open(calibrationFile);
  rtdb->setFirstInput(parIo1);

  // Create source using root files for input ---------------------------------
  R3BFileSource *source = new R3BFileSource(filename);
  source->SetInputFileName("../../../metafile.csv");
  run->SetSource(source);

  /* ------------ Setting Parameter Information ------------- */

  std::vector<metafile_data_struct> metafileEntries;
  Int_t lines = 0;

  struct metafile_data_struct metaElem;

  ifstream *metafile = new ifstream("../../../metafile.csv");

  while (!metafile->eof() && lines < 2) {

    *metafile >> hex >> metaElem.fRunID >> metaElem.fExpRun >>
        metaElem.fTimeStamp >> metaElem.califaMapVersion >>
        metaElem.califaCalVersion >> metaElem.califaGeoVersion;

    metafileEntries.push_back(metaElem);
    lines++;
  }

  metafile->close();

  Int_t fRunID;
  Int_t fCalifaCalVersion, fCalifaMapVersion, fCalifaGeoVersion;

  for (Int_t i = 0; i < metafileEntries.size(); i++) {

    fRunID = metafileEntries.at(i).fRunID;

    fCalifaMapVersion = metafileEntries.at(i).califaMapVersion;
    fCalifaCalVersion = metafileEntries.at(i).califaCalVersion;
    fCalifaGeoVersion = metafileEntries.at(i).califaGeoVersion;

    rtdb->addRun(fRunID);

    rtdb->setInputVersion(fRunID, (char *)"califaCrystalCalPar", fCalifaCalVersion, 1);
    rtdb->setInputVersion(fRunID, (char *)"califaMappingPar", fCalifaMapVersion, 1);
    rtdb->setInputVersion(fRunID, (char *)"CalifaGeoPar", fCalifaGeoVersion, 1);

    rtdb->initContainers(fRunID);
    rtdb->Print();
  }

  // Add analysis task --------------------------------------------------------

  // Add Header copy
  R3BEventHeaderPropagator *RunIdTask = new R3BEventHeaderPropagator();
  run->AddTask(RunIdTask);


  if (fCalifa) {

    // R3BWhiterabbitPropagator ---
    R3BWhiterabbitPropagator *wrcalifa = new R3BWhiterabbitPropagator( "CalifaWhiterabbitPropagator", 1, "WRCalifa");
    run->AddTask(wrcalifa);

     // R3BCalifaMapped2CrystalCal ---
    R3BCalifaMapped2CrystalCal *CalifaMap2Cal = new R3BCalifaMapped2CrystalCal();
    run->AddTask(CalifaMap2Cal);
  }


  // Initialize -------------------------------------------
   run->Init();

  // Run --------------------------------------------------
  if (nev > -1)
    run->Run(nev);
  else
    run->Run();

  // Finish -----------------------------------------------
  std::cout << "Macro finished succesfully." << std::endl;
  std::cout << "Output file is " << outputFilename << std::endl;
  gApplication->Terminate();
}
